### ISSUE TITLE
BIG FLAW IN YOUR PROJECT !

### ISSUE THREAD

**Issue by brijendra98** [nikshepsvn/py_noise#5]
Hi Nikshep,
You are using a dependency to generate random link so in this case the random link and the random link generator site always appear in pair in a user's browsing history. Don't you think filtering that out is the easiest think in the world for and ISP in the States ?

This flaw completely defeats the purpose of Scatterfly and you should do something to counter this.

--
Brijendra

**Comment by nikshepsvn** [comment]
Hey there Brijendra, did you mean 'Flaw' instead of 'Flow'? I want start off by thanking you for taking the time and going through the code to help me find issues. Yes, you are right about the fact that the 2 links will appear as a pair in the browser history of the user, but that does not affect the effectiveness of ScatterFly in any way as the 2 links being present in the log only serves as a way of identifying that ScatterFly has started running and provides no further information.

**Comment by nikshepsvn** [comment]
After looking through your statement more carefully, I understand what you're saying more clearly. Thank you for pointing this issue out to me as it is indeed very pressing -- I'm already working on eliminating all dependencies and I will do my best to get rid of the urroullete one too. Please feel free to follow the project and contribute!

**Comment by brijendra98** [comment]
Nah, I'm good !
